CONTA_CONTABIL_TARGET: str = "411"
DESCRIPTION_KEYWORDS: list[str] = [
    'EVENTO', 'SINISTRO', 'DESPESA COM EVENTO',
    'ASSISTENCIA', 'ASSISTÊNCIA', 'INTERNACAO', 'INTERNAÇÃO',
    'CONSULTA', 'EXAME', 'TERAPIA', 'PROCEDIMENTO'
]
